### ISSUE TITLE
[Feature Request] Crowdin: localization management platform

### ISSUE THREAD

**Issue by jont4** [FilenCloudDienste/filen-mobile#115]
Is there any chance to add i18n to a localization platform like Crowdin?
They have a free plan for open-source projects.

**Comment by DanielProg39** [comment]
To my opinion, these platforms make life harder as you need an account and the process of merging it with repo source code is not that transparent and overall editing the whole document is more convenient rather than translating it string by string as you can move back quickly and use the same words for the same things when there are several options available to provide same language stylistics through the application.

**Comment by jont4** [comment]
For those who translate it is much more practical to use a tool like Crowdin, write less and translate faster. Anyway, since the dev decided only to close this suggestion, I understood that it is something unwanted.

**Comment by lyonelf** [comment]
+1, crowdin is faster for translators.

And we receive push mail when lines are requested.

In less, make you a mailing list of translators and post lines to add to the .ts file ;)

**Comment by DanielProg39** [comment]
Well, maybe I'm too technical. I've seen projects using Crowdin (I've used it once), Weblate, Poeditor and you should have an account in each of these to provide translations. While translating in these platforms might be a bit more convenient as you have this shiny GUI and notifications, I'm a minimalist and I don't think it's worth creating additional accounts and relying on 3rd party services to do the same work just a bit differently. It's not that difficult to translate strings in the file itself, rather than using a third-party service to do essentially the same work.

However, I have to admit that using services like Crowdin makes life easier for people who are not familiar with Git and development.

**Comment by lyonelf** [comment]
Understand.

So how can i have some mail alerts when you add lines who need translation?

**Comment by jont4** [comment]
> Well, maybe I'm too technical. I've seen projects using Crowdin (I've used it once), Weblate, Poeditor and you should have an account in each of these to provide translations. While translating in these platforms might be a bit more convenient as you have this shiny GUI and notifications, I'm a minimalist and I don't think it's worth creating additional accounts and relying on 3rd party services to do the same work just a bit differently. It's not that difficult to translate strings in the file itself, rather than using a third-party service to do essentially the same work.
> 
> However, I have to admit that using services like Crowdin makes life easier for people who are not familiar with Git and development.

I'm advanced user and a dev, familiar with git, and... something like Crowdin helps the translation a lot, makes the process faster and much less complicate. This is not a matter of taste, the translation using Crowdin is much faster, fact. It suggests translations, you can easily compare with translations from other languages, as well as several other facilities.
