### ISSUE TITLE
 [Feature Request] Sync options the same as in the desktop application.

### ISSUE THREAD

**Issue by JumpProg** [FilenCloudDienste/filen-mobile#131]
Implement the sync solution as in the desktop application (selection of different folders etc.):

Sync options:

-     two way,
-     local to cloud,
-     cloud to local,
-     local backup,
-     cloud backup.

**Comment by DanielProg39** [comment]
Yeah, this will help a lot. Syncing photos is good but I also want to sync a couple folders with other data. Now I need to upload new files from these folders by hand. But I actually think that all syncing functionality from a desktop app should be ported to mobile, because features like ".filenignore" really make life easier.

**Comment by jnolan7599** [comment]
I was rather surprised this wasn't already the case.

**Comment by Dwynr** [comment]
Rel: https://github.com/FilenCloudDienste/filen-mobile/issues/150
