### ISSUE TITLE
Preserve GPS and camera information in photo metadata

### ISSUE THREAD

**Issue by skauertz** [FilenCloudDienste/filen-mobile#195]
Since 2.0.44 the photos uploaded from the camera correctly preserve the original date of the photo, that's great!

However, I want to suggest also to include the camera information and GPS data in the metadata if possible.

**Comment by szapp** [comment]
@Dwynr Possibly related to this issue and the FAQ "Why does the Metadata gets modified while uploading photos via the automatic camera upload on iOS?":

I noticed that, on iOS, the metadata (including GPS and camera information) is indeed preserved during automatic camera upload when "Do not convert HEIC/HEIF" is selected. However, without this setting, the uploaded JPGs are stripped of their metadata.

If this is still an open problem, I wanted to share this observation. Maybe the dropped metadata occurs due to the method of JPG conversion (i.e. either provided by the iOS or converted by Filen itself).
