### ISSUE TITLE
[Feature request] Camera Upload add option for subfolders

### ISSUE THREAD

**Issue by KushGene** [FilenCloudDienste/filen-mobile#67]
I would like to have my photos & videos to be sorted into subfolders like Date -> Month -> ( pictures of month). So there should be an option at Camera Upload, to upload in folders. Maybe add some variant options.

**Comment by torbjokv** [comment]
I would also love this feature! In addition, the filenames would be better if they where composed of a date instead of the guid that is used today. When I sync my pictures today (iphone), both timestamps is replaced with the sync time and my original picture time is completely lost when they land on my macbook afterwards. I would maybe consider this a bug?

Example of how I would prefer it: .../Filen Sync/Camera Upload/2022-05/2022-05-15-11.32.33.035.heic

Keep up the great work!

**Comment by skauertz** [comment]
There should also be an option to automatically sort the uploaded pictures into a sub-folder named after the Album they are associated to (on iOS, not sure how it works on Android). Right now in 2.0.44 you can already select separate Albums to synchronize, but then they all get thrown into the same folder.

**Comment by youdontneedtoknow22** [comment]
> There should also be an option to automatically sort the uploaded pictures into a sub-folder named after the Album they are associated to (on iOS, not sure how it works on Android). Right now in 2.0.44 you can already select separate Albums to synchronize, but then they all get thrown into the same folder.

THIS PLEASE

**Comment by ialexpw** [comment]
+1 to the previous. Just tried this and noticed everyone gets dumped into one folder. Used NC before which organised it based on Album.

**Comment by Dwynr** [comment]
Added.

https://github.com/FilenCloudDienste/filen-mobile/pull/288/commits/f500ff441700ba85e7be098291c881aa02532fcd
